CREATE TABLE Users(

UserId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
UserName VARCHAR(25) NOT NULL,
Password VARCHAR(25) NOT NULL,
Email VARCHAR(50) NOT NULL,
Gender CHAR(2) CHECK(Gender IN ('e','k')),
Auth VARCHAR(15)
)
ALTER TABLE Users ALTER COLUMN Gender CHAR(2) NOT NULL;

